module.exports = {
  apps: [
    // ── Backend Services ────────────────────────────────────────────────────
    {
      name: 'identity-service',
      cwd: './services/identity-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3001 },
    },
    {
      name: 'course-service',
      cwd: './services/course-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3002 },
    },
    {
      name: 'content-service',
      cwd: './services/content-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3003 },
    },
    {
      name: 'enrollment-service',
      cwd: './services/enrollment-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3004 },
    },
    {
      name: 'assessment-service',
      cwd: './services/assessment-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3005 },
    },
    {
      name: 'progress-service',
      cwd: './services/progress-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3006 },
    },
    {
      name: 'grade-service',
      cwd: './services/grade-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3007 },
    },
    {
      name: 'commerce-service',
      cwd: './services/commerce-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3008 },
    },
    {
      name: 'notification-service',
      cwd: './services/notification-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3009 },
    },
    {
      name: 'staff-service',
      cwd: './services/staff-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 3010 },
    },

    // ── Frontend (Next.js) ──────────────────────────────────────────────────
    {
      name: 'frontend',
      cwd: './frontend',
      script: 'node_modules/.bin/next',
      args: 'start -p 4000',
      instances: 1,
      autorestart: true,
      watch: false,
      env_production: { NODE_ENV: 'production', PORT: 4000 },
    },
  ],
};
